### ISSUE TITLE
Updating Laravel to 8.*

### ISSUE THREAD

**Issue by krzysztofrewak** [Equipment-Manager/Equipment-Manager#34]
Hello there! 

I think you should seriously reconsider updating Laravel framework to `^8.0`. Right now it should be extremely easy (as is documented [here](https://laravel.com/docs/8.x/upgrade#upgrade-8.0)). Remember that moving from 7 to 8 now is simpler than moving from 7 to 9 next year. ;)

**Comment by agawle** [comment]
Actually we were thinking about moving whole project to .NET, as we always wanted to try it :wink:

**Comment by krzysztofrewak** [comment]
Okay, I updated Laravel for your project, but it's impossible to push new branch. Please fix that.

```
15:51:29.062: [equipment-manager] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/#34-updating-laravel:#34-updating-laravel --set-upstream
remote: Permission to Equipment-Manager/Equipment-Manager.git denied to krzysztofrewak.
fatal: unable to access 'https://github.com/Equipment-Manager/Equipment-Manager.git/': The requested URL returned error: 403
```
